### ISSUE TITLE
Compiling on Linux stops abruptly

### ISSUE THREAD

**Issue by ItsRogueRen** [you-win/openseeface-gd#2]
So I have been trying to compile this for Linux, but upon choosing to export after installing the Linux preset I get the loading bars for a few seconds before going away and leaving me with a file that does nothing when launched. The progress bar gets to about 40% before vanishing (crashing?) The resulting executable has executable permission. If there's an error code its there too quickly for me to see it. I've tried both Godot from the official page and compiling your fork with the same results.

**Comment by you-win** [comment]
The premade Linux presets won't work since this project uses a custom build of Godot. Seeing as you can already compile my fork of Godot, run something like `scons platform=x11 target=release` to generate a custom template for Linux and then export the project using that new template (Project > Export > Options (tab) > Custom Template (section) > Release. Let me know if that doesn't work, and I can try compiling this on my old Linux box.

**Comment by ItsRogueRen** [comment]
What directory would I need to be in? The same as where I compiled Godot?

**Comment by you-win** [comment]
Yes. Creating export templates is the same process as compiling the engine. Fun fact, the editor and the release_debug export template are the same binary.

By the way, are you able to run the project from the editor?

**Comment by ItsRogueRen** [comment]
I tried that with no change in result, though I could only run it as debug or release_debug (I went with release_debug)

Hitting play in the project launches a window with a Godot logo splash screen, but that's all. It doesn't crash, but it appears to be frozen as I have a loading icon by my cursor when my mouse is over the window, but the animation for the cursor isn't moving (though that could just be KDE acting up)

**Comment by ItsRogueRen** [comment]
> Ah, that means that you probably did not compile the correct branch on my Godot fork. In the godot directory, switch to the 3.2-gltf branch (`git checkout 3.2-gltf`), and then recompile using that.

I don't see a release for 3.2-gltf, only for 3.2-stable
I followed the link on this page, and its in your repo

**Comment by you-win** [comment]
It's not a release, the code is on a git branch. Do you have git installed on your system? For Debian-based distros (Ubuntu, Pop), `sudo apt install git` and for RHEL-based distros (Fedora, CentOS) `sudo yum install git` or `sudo dnf install git` should work.

**Comment by ItsRogueRen** [comment]
Oh my god I'm dumb, yes I have git. Lol

**Comment by you-win** [comment]
No worries, the entire build-from-source process isn't very straightforward.

**Comment by ItsRogueRen** [comment]
> No worries, the entire build-from-source process isn't very straightforward.

Yeah, I'm actually trying to write and record a tutorial for this so that others don't have to go through this chaos, only I will lol. Appreciate the help and I currently recompiling Godot right now so I'll find out soon if it works!

**Comment by ItsRogueRen** [comment]
I got an error when compiling godot

modules/gltf/register_types.cpp:68:14: error: incomplete type 'EditorNode' used in nested name specifier
   68 |  EditorNode::add_init_callback(_editor_init);
      |              ^~~~~~~~~~~~~~~~~
scons: *** [modules/gltf/register_types.x11.tools.64.o] Error 1
scons: building terminated because of errors.

**Comment by you-win** [comment]
So it looks like I committed some bad code without compiling first.

In `modules/gltf/register_types.cpp` at line 33: uncomment that line. I'm not sure why I did that.

**Comment by ItsRogueRen** [comment]
> So it looks like I committed some bad code without compiling first.
> 
> In `modules/gltf/register_types.cpp` at line 33: uncomment that line. I'm not sure why I did that.

That fixed the initial error, but now there are more

[Initial build] Compiling ==> editor/quick_open.cpp
{standard input}: Assembler messages:
{standard input}:932910: Warning: end of file in string; '"' inserted
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[Initial build] Compiling ==> editor/register_exporters.gen.cpp
[Initial build] Compiling ==> editor/rename_dialog.cpp
[Initial build] Compiling ==> editor/reparent_dialog.cpp
[Initial build] Compiling ==> editor/run_settings_dialog.cpp
[Initial build] Compiling ==> editor/scene_tree_dock.cpp
[Initial build] Compiling ==> editor/scene_tree_editor.cpp
scons: *** [editor/editor_fonts.x11.tools.64.o] Error 1
scons: building terminated because of errors.

**Comment by you-win** [comment]
How much RAM/swap does your machine have? That looks like it could be an insufficient memory issue. I'm able to compile the engine and run the project on Windows.

**Comment by ItsRogueRen** [comment]
> How much RAM/swap does your machine have? That looks like it could be an insufficient memory issue. I'm able to compile the engine and run the project on Windows.

I have 8GB on my laptop I'm using right now, and when I get home I'll have 16GB on my desktop. If it is a memory issue I may just have to wait and do it on my desktop

**Comment by ItsRogueRen** [comment]
> The premade Linux presets won't work since this project uses a custom build of Godot.
> 
> Seeing as you can already compile my fork of Godot, run something like `scons platform=x11 target=release` to generate a custom template for Linux and then export the project using that new template (Project > Export > Options (tab) > Custom Template (section) > Release.
> 
> Let me know if that doesn't work, and I can try compiling this on my old Linux box.

I cannot find where this options tab is in the export menu, nor the file created from `scons platform=x11 target=release` 
I have successfully (I think) compiles the custom Godot and the preset, however my only option is still the default Linux export. Hitting play does start the program in Godot, but in the export menu I have an error at the bottom of the window that says I'm missing export presets for this version. Clicking on manage presets show that the missing one is 3.2.4.rc

**Comment by you-win** [comment]
I recommend following the [instructions in the docs for Linux/X11](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html). These detail everything you need to know regarding compiling the engine/export templates.

For what it's worth, I am able to compile the engine + export templates + export the project (in debug mode) on Pop OS 20.04. You will need to run the facetracker via Python, so follow the instructions in the [OpenSeeFace repo](https://github.com/emilianavt/OpenSeeFace).

![Screenshot from 2021-03-13 03-40-16](https://user-images.githubusercontent.com/7788341/111024730-50518500-83ae-11eb-96c2-b8a33f76e79a.png)

**Comment by ItsRogueRen** [comment]
> I recommend following the [instructions in the docs for Linux/X11](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html). These detail everything you need to know regarding compiling the engine/export templates.
> 
> For what it's worth, I am able to compile the engine + export templates + export the project (in debug mode) on Pop OS 20.04. You will need to run the facetracker via Python, so follow the instructions in the [OpenSeeFace repo](https://github.com/emilianavt/OpenSeeFace).
> 
> ![Screenshot from 2021-03-13 03-40-16](https://user-images.githubusercontent.com/7788341/111024730-50518500-83ae-11eb-96c2-b8a33f76e79a.png)

I have already done that. The program works, I just can't find the button to export with a custom preset.

![godo_export_Screenshot_20210313_091614](https://user-images.githubusercontent.com/75085610/111034832-fe742380-83dc-11eb-9292-1299d81469cc.png)

**Comment by you-win** [comment]
Click on Add > Linux/X11
If you get an error that no template presets are present, then copy the binary you compiled to the path given in red. Should be something like `cp /path/to/godot/bin/binary-name $HOME/.local/share/godot/3.2.4.rc/` and then rename the binary to whatever the error tells you. This will probably be `linux_x11_64_debug`.
If you already have the template presets downloaded (aka the ones that won't work), there will be a field for custom templates. Provide a path to the binary you compiled in `/path/to/godot/bin/binary-name`.
![Untitled](https://user-images.githubusercontent.com/7788341/111036731-b65dfc80-83ee-11eb-86dd-2adb21b70974.png)

**Comment by ItsRogueRen** [comment]
It worked!!! My binary had a different name, `godot.x11.tools.64` but after choosing that it did compile correctly! 

Thanks for all the help, and I'm sorry I seemed like an idiot sometimes lol. I'm REALLY bad with compiling from source and ADHD, which is not a fun combination.

**Comment by you-win** [comment]
Great! You'll want to compile a release template eventually (or I'll get around to providing a Linux release once more things are done) by compiling with `target=release`.

Closing the issue.
