### ISSUE TITLE
VRM Outline (MToon port?)

### ISSUE THREAD

**Issue by ItsRogueRen** [you-win/openseeface-gd#26]
Outline with VRM models using MToon shader doesn't render correctly or at all

Example of correct and incorrect rendering:

![ren-outline-example](https://user-images.githubusercontent.com/75085610/124058278-ae05ed80-d9ee-11eb-95d8-9777d843e36a.png)

**Comment by you-win** [comment]
fixed by [this commit to master](https://github.com/you-win/openseeface-gd/commit/30d78bfff061d1a08f5e06b382a20f41fef8c0f0)
