### ISSUE TITLE
Linux Release glibc

### ISSUE THREAD

**Issue by happyeggchen** [you-win/openseeface-gd#29]
OS:debian buster
When u try to run it on this,it can't be launched and print
```
./OpenSeeFace-gd.x86_64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./OpenSeeFace-gd.x86_64)
```
It come with a package but upgrade that is too dangerous

**Comment by ItsRogueRen** [comment]
The built version is made with Ubuntu 20.04 LTS in mind, Debian may be behind on some things.

**Comment by happyeggchen** [comment]
Can i build
 it by myself using godot(modified)?

**Comment by ItsRogueRen** [comment]
> Can i build
>  it by myself using godot(modified)?

You should be able to. You'll have to compile an export profile with the custom fork and then use that to build it. I don't know the exact details as I can just use a provided one in one of Youwin's other repos for an export profile. No sure if it'll work for Debian.

**Comment by happyeggchen** [comment]
[debug.log](https://github.com/you-win/openseeface-gd/files/6773556/debug.log)
I complied it successfully but it can't exec.
Heres the log maybe you can point what wrong here

**Comment by happyeggchen** [comment]
Never i found 2 way to get it run
 -run it in godot debug mode
 -upgrade debian to bullseye or higher release like sid

**Comment by you-win** [comment]
@ItsRogueRen thanks for helping resolve this!

@happyeggchen  I took a look at your debug log and it looks like PulseAudio terminated early for some reason. Did you compile a release template using `scons platform=x11 target=release tools=no` ? And did you make sure you have the required packages on your system? [Godot docs](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html) I'm thinking your pulse audio library is possibly too old?

**Comment by happyeggchen** [comment]
@you-win Could u give a commandline of how to build it from console,i will give it a try

**Comment by you-win** [comment]
that was the command line argument. Run `apt install scons` if you don't already have `scons` available. You can also pass a `-j` flag to define how many threads to use when building.

The final command I would run for linux would be `scons platform=x11 target=release tools=no -j4`

**Comment by happyeggchen** [comment]
I run it in OpenSeeFace-gd folder and it printed
```
scons: *** No SConstruct file found.
```

**Comment by you-win** [comment]
You need to use it to build the Godot release template. Do not run it in the OpenSeeFace-gd folder. Run it in the Godot engine folder.

If you are building from master, [clone the main Godot repo](https://github.com/godotengine/godot), make sure you are on the `3.x` branch, and run the command.

If you are building from the stable release, [clone my Godot fork](https://github.com/you-win/godot), make sure you are on the `3.3-gltf` branch, and run the command.

**Comment by happyeggchen** [comment]
But there's already a bin file in your godot engine repo...i use the bin file

**Comment by you-win** [comment]
Yes, but you were having trouble running the release. My thinking was: if you can build the Godot release template, then you should be able to run the release version of OpenSeeFace-GD. If not, then that is a bug on the Godot-side.

If running the application via debug mode is good enough for you, then this issue can be closed.

**Comment by happyeggchen** [comment]
Best way to deal with this it to switch debian stable to debian testing or Sid,much more stable
