### ISSUE TITLE
Twisted model when tracking starts

### ISSUE THREAD

**Issue by ItsRogueRen** [you-win/openseeface-gd#3]
So my model is twisted and leaning down with the arms T-Posed. I don't know why, but I'm 99% sure that isn't supposed to happen. Model works in other VRM programs just fine and in Unity without issue. 

Screenshot:
![image](https://user-images.githubusercontent.com/75085610/115768731-52750f00-a370-11eb-91f6-45747e9689b6.png)

The program does track, I can see the head move when I move, and the eyes blink and mouth moves when I speak. Its just the default values seem to all be wrong.

**Comment by you-win** [comment]
### Solution
The face tracking offsets need to be set/reset. Press the `spacebar` key or the `Set offsets` button in the UI and your model should track normally.

### Reason
 The face tracker returns data that is slightly skewed by default. The program should set the offsets automatically but the timing seems to be off.

Thanks for the report!
