### ISSUE TITLE
Bones with a period character "." in the name cannot be found when posing the model

### ISSUE THREAD

**Issue by you-win** [you-win/openseeface-gd#35]
1. Go to the pose menu
2. Select a bone to modify that has a "." in the name (e.g. Left.UpperArm)
3. Click on "Apply properties"
4. Observe that nothing happens

Suggested resolution: Store bone names elsewhere (i.e. not as the node name)

**Comment by Zutatensuppe** [comment]
Is this still relevant? What is the 'pose menu'?

**Comment by you-win** [comment]
This is probably still relevant. Before the UI rewrite, there used to be a menu for posing bones. Now, that option is included next to each bone in the Model view.

The problem was that Godot does not allow for Node names to have a '.' in the name. I think each bone option just used the bone name as the Node name, so Godot silently converted the '.' to a '_'. This broke some mappings, I think.

**Comment by Zutatensuppe** [comment]
Oh ic, in the current version i can move/pose bones that have a dot in them, so it seems to work fine ^^

**Comment by you-win** [comment]
Nice! I guess I fixed this by accident during the rewrite. Closing the issue.
