### ISSUE TITLE
[Request] Linux release

### ISSUE THREAD

**Issue by 0xngmi** [you-win/openseeface-gd#5]
It would be nice to get a linux release so we can avoid compiling from source

**Comment by you-win** [comment]
I don't have the Linux toolchain on my main development machine (Windows 10). The project is still under heavy development, but once it gets to a stable release, I can provide Linux builds.

**Comment by you-win** [comment]
I've uploaded a Linux build under [releases](https://github.com/you-win/openseeface-gd/releases/tag/0.5.0).

**Comment by 0xngmi** [comment]
Thanks!
