### ISSUE TITLE
Running the tracker from the application causes a crash on Linux

### ISSUE THREAD

**Issue by you-win** [you-win/openseeface-gd#52]
The error in the logs is something to the effect of "Unable to call function _start_tracker"

The issue is somewhere in `OpenSeeGD.gd` at line 269 when generating run options.

**Comment by Zutatensuppe** [comment]
Does this happen also with a clean master checkout? (creating tracker options starts at line 264 for me)
I m sorry if that was caused with my pr, I didn't get that message when testing it ><

**Comment by you-win** [comment]
@Zutatensuppe Nah, this was one of my changes from the 0.7.1 release. I'm passing terminal arguments incorrectly on Mac/Linux. In the exported builds, it crashes the entire program when starting the tracker.

**Comment by you-win** [comment]
Fixed by 40382e0332ba416e742eeee223b4703effd23bcc
