### ISSUE TITLE
transparent background is broken on linux

### ISSUE THREAD

**Issue by xfnw** [you-win/openseeface-gd#73]
on linux with xorg and picom, enabling transparent background just makes the background black

weirdly, the godot splash screen has correctly functioning transparency

**Comment by ItsRogueRen** [comment]
in app settings turn off "use FXAA"

FXAA disables transparency in Godot so if you want the best Anti-Aliasing (both FXAA and MSAA) you'll need to chroma key, but just using MSAA will allow transparency

**Comment by xfnw** [comment]
ah, thanks
