### ISSUE TITLE
VRM Arm Auto-Mapping

### ISSUE THREAD

**Issue by ItsRogueRen** [you-win/openseeface-gd#8]
I talked to Emilianna a little bit and she said that VRM part names don't actually matter, and you should use the humanoid bone mapping in the avatar descriptor.

![Screenshot_20210529-091018_CutTheCord.jpg](https://user-images.githubusercontent.com/75085610/120075199-eae46a80-c065-11eb-85fb-15bb9758d482.jpg)

https://github.com/vrm-c/vrm-specification/tree/9a02cc2302c4c656e404fc1d505e9d9c4895d04d/specification/0.0#vrm-extension-models-bone-mapping-jsonextensionsvrmhumanoid

**Comment by you-win** [comment]
You know what, that makes complete sense. I'm actually already doing that for automatically mapping the head to the face tracker, but it didn't occur to me that I could do the same thing for the arms.

**Comment by you-win** [comment]
Should be fixed by #12

**Comment by you-win** [comment]
closing as part of cleanup
