### ISSUE TITLE
[Request] Body tracking

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [you-win/openseeface-gd#99]
As far as I know, OpenSeeFace does not support any tracking other than face. Is arm tracking going to be added?

**Comment by ItsRogueRen** [comment]
> As far as I know, OpenSeeFace does not support any tracking other than face. Is arm tracking going to be added?

Not in this software, eventually this will be rewritted into a more polished version on the newest Godot version called Virtual Streamer Software. VSS will eventually have hand tracking via either MediaPipe webcam tracking or with LeapMotion devices.

**Comment by you-win** [comment]
LeapMotion support is the only planned addition, but that will be after a 1.0.0 release and will probably be backported from [vss](https://github.com/vss-project/vss) anyways.

Anything more advanced like MediaPipe or iFacialMocap is planned for [vss](https://github.com/vss-project/vss).

> Thanks, is there any ETA for the new software?

There's no ETA for a 1.0.0 release of openseeface-gd or for hand tracking in general. I don't know enough about hand tracking at this point in time to give a reasonable estimate.

openseeface-gd 0.8.1 is slated for release this week which has better Linux support + initial support for remotely controlling the app

**Comment by ItsRogueRen** [comment]
Not really, its just whenever Youwin gets all the basics working in this software

**Comment by EmiliaTheGoddess** [comment]
Got it, thank you for the help and working on the program.

**Comment by OCsonic** [comment]
What happened to vss-project/vss ?

**Comment by iamwacko** [comment]
Body tracking doesn't seem to have been implemented yet, shouldn't this be re-opened?

**Comment by ItsRogueRen** [comment]
> Body tracking doesn't seem to have been implemented yet, shouldn't this be re-opened?

No as it is not currently planned. If You-win deciders otherwise it will be, but that's his call to make.
